name: 'Ensure Clean Jupyter Notebooks'
description: 'Enforce rules on certain cells and metadata in Jupyter Notebooks'
inputs:
  disable-checks:
    description: 'Optional list of linting checks to disable'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
